name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      test-command: |
        # Dependencies not declared in "blscurve.nimble" as they are only used
        # for testing:
        nimble install -y stint
        pushd tests
        bash download_ef_bls12381_vectors.sh
        popd
        # Run the tests.
        nimble test
